#!/bin/bash
echo ""
clear
echo ""
echo -e ""
echo ""
echo ""
echo -e ""
echo -e " \e[1;33m[\e[0m\e[1;77m~\e[0m\e[1;33m]\e[0m\e[1;32m \e[95m SUBSCRIBE ME CHANNEL \e[0m"
echo ""
echo -e " \e[91m[\e[92m*\e[91m]\e[1;93m Subs My channel :\e[0m\e[1;36m https://youtube.com/channel/UCG_zgIRcf9wRnzsuMpz3aMQ  "
echo ""
echo ""
echo ""
read -p $'\e[1;40m\e[31m[\e[32m*\e[31m]\e[32m Subscribe to Complete ? \e[1;91m (Y/N) : \e[0m' option
echo""
echo""
echo""
if [[ $option == *'N'* ]]; then
clear
exit
fi
if [[ $option == *'n'* ]]; then
clear
exit
fi
clear
echo ""
echo -e " \e[1;33m[\e[0m\e[1;77m~\e[0m\e[1;33m]\e[0m\e[1;32m Installing Hack fb Tool Please Wait....  \e[0m"
echo -e ""
clear
echo ""
echo ""
echo -e "\e[1;33m[\e[0m\e[1;77m~\e[0m\e[1;33m]\e[0m\e[1;32m Installing Hackfb tool  Please Wait....  \e[0m"
echo ""
echo -e $'\e[1;91m\e[0m\e[1;91m\e[0m\e[1;96m\e[0m\e[1;91m   ----------------------------------------  \e[1;91m\e[0m'
echo -e $'\e[1;96m\e[0m\e[1;77m\e[0m\e[1;96m\e[0m\e[1;91m  !!         DOWNLOAD REQUIREMENTS         !!\e[0m'
echo -e $'\e[1;91m\e[0m\e[1;91m\e[0m\e[1;96m\e[0m\e[1;91m   ----------------------------------------- \e[1;91m\e[0m'
echo ""
echo -e "\e[1;33m[\e[0m\e[1;77m~\e[0m\e[1;33m]\e[0m\e[1;32m \e[95m X ArynzClem \e[0m"
echo ""
sleep 2
termux-setup-storage
apt-get update -y
apt-get upgrade -y
pkg install python
pip install bs4
pip install requests
pip install rich
pip install wheel
clear
echo '
      ---------------------------------   
    !!    Installation Successfull     !!  
      ---------------------------------   ' | 
sleep 2
clear
echo
xdg-open https://youtube.com/channel/UCG_zgIRcf9wRnzsuMpz3aMQ
sleep 3
echo -e FREE COOKIES=datr=039SY5y90eAkLKHGwC6nlEr0;sb=039SY8o935rm1lG3u_snbzOs;fr=01FixhlyptEhEDBOC.AWV4L6zeYoCV4G8xCIEzomuGzcE.BjUn_T.HR.AAA.0.0.BjUn_b.AWVETGD0b3E;c_user=100085774461633;xs=21%3AXcbyHIo6icDBbQ%3A2%3A1666351068%3A-1%3A15782;m_page_voice=100085774461633;wd=360x566;
wait a 5 sec
sleep 5
python crack.py
